# Generated by Django 5.1 on 2024-08-12 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0002_remove_auto_color_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='año',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='auto',
            name='marca',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='auto',
            name='modelo',
            field=models.CharField(max_length=100),
        ),
    ]
